# path to the training dataset
training_dataset_path: /path/train.h5
# path to the training dataset
validation_dataset_path: /path/validation.h5
# path to normalized data with {} as placeholder for the subjects
data_path: /path/{}/data.nii.gz
# path to the b-vector file with {} as placeholder for the subjects
bvecs_path: /path/{}/bvecs
# path to the b-values file with {} as placeholder for the subjects
bvals_path: /path/{}/bvals
# path to the mask file with {} as placeholder for the subjects (mask for white and grey matter voxels)
mask_path: /path/{}/mask.nii.gz
# path to save experiment results, e.g. the checkpoint
experiment_path: /path/
# list of training subjects
training_subject_ids: ["subject_1", "subject_2", "subject_3"]
# list of validation subjects
validation_subject_ids: ["subject_1", "subject_2", "subject_3"]
# list of test subjects
test_subject_ids: ["subject_1", "subject_2", "subject_3"]
# list of names for the observation sets
observation_set_names: ["10", "20", "30"]
# list of lists of indices for the observation sets (must have the same length as observation_set_names)
observation_set_indices: [["indices_for_subset_of_10"], ["indices_for_subset_of_20"], ["indices_for_subset_of_30"]]
# path to the prediction file including filename with {} as placeholders for the subject_id and for the observation_set_name
prediction_path: /path/{}/prediction_{}.nii.gz
